---
- hosts: myapplicationserver
  become: yes
  tasks:
  - include_tasks: file.yml
  - name: i want to install a webserver
    apt:
     name: apache2
     state: present
  - name: i want to copy files into node side
    template:
       src: src.j2
       dest: var/www/html/index.html