---
- hosts: mywebsever
  become: yes
  tasks:
  - name: i want to install apache2 on ubuntu node server
    apt:
     name: apache2
     state: present   
    when: ansible_os_family=="debian"

  - name: i want to install apache2 on ubuntu node server
    apt:
     name: apache2
     state: started

  - name: i want to install a httdp on RedHat nodes
    yum:
     name: httdp
     state: present
    when: ansible_os_family=="RedHat"
    
  - name: i want to install httdp on RedHat node server
    yum:
     name: httdp
     state: started
    
     

