---
- hosts: 172.31.42.225
  become: yes
  vars:
    var1: git
    var2: tree
    var3: wget
  tasks:
  - name: i want to display var1
    debug:
      msg: "{{var1}}"
  - name: i want to install git
    apt:
     name: "{{var1}}"
     state: present
  loop: 
    - "{{var1}}"
    - "{{var2}}"
    - "{{var3}}"