
---
- hosts: all
  tasks:
  become: yes
- name: i want to install a apache2 on "RedHat" ansible node server
  yum: 
   name: httdp
   state: present
  when: ansible_os_family =="RedHat"

- name:  i want to install a apache2 on RedHat ansible node server
  service:
    name: httdp
    state: started
  when: ansible_os_family =="RedHat"
  