---
- hosts: all
  tasks:
  become: yes
- name: i want to install a apache2 on ubuntu ansible node server
  apt: 
   name: apache2
   state: present
  when: ansible_os_family =="debian"

- name:  i want to install a apache2 on ubuntu ansible node server
  service:
    name: apache2
    state: started
  when: ansible_os_family =="debian"
  