
---
- hosts: all
  tasks:
  become: yes
- name: i want to install   "RedHat" on ansible node server
  yum:
   name: httdp
   state: started
  when: ansible_os_family =="RedHat"

- name:  i want to install   RedHat on ansible node server
  service:
    name: httdp
    state: started
  when: ansible_os_family =="RedHat"


- name: i want to install   "apache2" on ansible node server
  apt:
   name: apache2
   state: started
  when: ansible_os_family =="debian"

- name:  i want to install   apache2 on ansible node server
  service:
    name: apache2
    state: started
  when: ansible_os_family =="debian"


